@startuml

hide circle
hide empty fields
hide empty methods

skinparam class {
    backGroundColor white
    borderColor black
    arrowColor black
    
}

skinparam {
    shadowing false
    ranksep 30
    dpi 300
    arrowThickness 1
    defaultFontSize 12
    arrowFontSize 8
}

class "Info" as info
class "Pocket" as pocket
class "Instapaper" as instapaper
class "Notion" as notion
class "(Gmail)" as gmail
class "Dynalist" as dynalist

info -> pocket
info -> instapaper
instapaper -> gmail : IFTTT (use folder)
pocket --> instapaper
gmail --> dynalist : Dynalist Email to Inbox
dynalist - notion

@enduml