@startuml

hide circle
hide empty fields
hide empty methods

skinparam class {
    backGroundColor white
    borderColor black
    arrowColor black
}

skinparam {
    shadowing false
    ranksep 30
    dpi 300
    arrowThickness 1
    defaultFontSize 12
    arrowFontSize 8
}

class "Dynalist" as dynalist {
    ノート
    データベース
    タスク管理
    リマインド（管理）
}

class "Google Drive" as googledrive {
    クラウドストレージ
}

class "Visual Studio Code" as visualstudiocode {
    Plant UML によるチャートの作成
}

class "Diagrams" as diagrams {
    複雑な図の作成
}

class "Excalidraw" as excalidraw {
    手書き風の簡易図の作成
}

class "Google Drawings" as drawings {
    表の作成（エクスポート）
}

class "Sheets" as sheets {
    表の作成（作成）
}

class "XChange" as xchange {
    PDF の閲覧と編集
}

class "Dynawrite" as dynawrite {
    スマホからタスクを追加
}

class "Obsidian" as obsidian {
    スマホ閲覧をメインとしたノート
}

class "Google Keep" as googlekeep {
    スマホ用のメモ
}

class "Google Calendar" as googlecalendar {
    スケジュールの管理（カレンダー）
}

class "（Gmail）" as gmail {
}

class "LINE" as line {
    リマインド（通知）
}

class "Todoist" as todoist {
    スケジュールの管理（一覧）
}


googlecalendar -- dynalist
googlecalendar -- todoist
googlecalendar -- gmail
gmail -- line
dynalist -- googledrive
googledrive -- visualstudiocode
googledrive -- diagrams
googledrive -- excalidraw
googledrive -- drawings
drawings -- sheets
googledrive -- xchange
dynawrite -- dynalist


@enduml