@startuml

hide circle
hide empty fields
hide empty methods

skinparam class {
    backGroundColor white
    borderColor black
    arrowColor black
}

skinparam {
    shadowing false
    ranksep 30
    dpi 300
    arrowThickness 1
    defaultFontSize 12
    arrowFontSize 8
}



package "ノート" <<rectangle>> {
    Class "Logseq" as logseq
    class "VS Code" as vscode
    class "Diagrams" as diagrams
    class "Excalidraw" as excalidraw
    class "Plant UML" as plantuml
    class "PDF" as pdf
}

package "メモ" <<rectangle>> {
    class "Google Keep" as googlekeep
    class "Local Files" as localfiles
    class "QuickEdit" as quickedit
}

package "データベース" <<rectangle>> {
    class "Google Sheets" as googlesheets
    class "Notion" as notion
    class "Coda" as coda
}

package "タスク管理" <<rectangle>> {
    class "Dynalist" as dynalist
    class "Dynawrite" as dynawrite
    class "Todoist" as todoist
    class "Google Calendar" as googlecalendar
    class "Gmail" as gmail
    class "LINE" as line
}

'ノート
logseq <-- vscode
vscode -- plantuml
vscode -- excalidraw
vscode -- diagrams
logseq <-- pdf

'メモ
localfiles --> quickedit

'データベース

'タスク管理
googlecalendar <-- dynalist
googlecalendar <--> todoist
googlecalendar --> gmail
gmail --> line
dynawrite -> dynalist

@enduml