@startuml

hide circle
hide empty fields
hide empty methods

skinparam class {
    backGroundColor white
    borderColor black
    arrowColor black
}

skinparam {
    shadowing false
    ranksep 30
    dpi 300
    arrowThickness 1
    defaultFontSize 12
    arrowFontSize 8
}

class "Google Keep" as googlekeep
class "Google Sheets" as googlesheets
class "Airtable" as airtable
class "Simplenote" as simplenote
class "Notion" as notion
class "Dynalist" as dynalist
class "Dropbox" as dropbox
class "Visual Studio Code" as vscode
class "Diagrams" as diagrams
class "Excalidraw" as excalidraw
class "Plant UML" as plantuml
class "XChange" as xchange
class "Dynawrite" as dynawrite
class "Google Calendar" as googlecalendar
class "Todoist" as todoist
class "Gmail" as gmail
class "LINE" as line


googlecalendar <-- dynalist
googlecalendar <--> todoist
googlecalendar --> gmail
gmail --> line
dynalist -- dropbox
dropbox -- vscode
vscode -- diagrams
vscode -- excalidraw
vscode -- plantuml
dropbox -- xchange
dynawrite --> dynalist


@enduml