@startuml

skinparam {
    dpi 300
    defaultFontName Meiryo
    defaultFontSize 12
}

title
|= 項目名 |= 表記 |= 規則説明 |
| 漢字 | <#> | 特記事項なし |
| ひらがな | <#black> | 特記事項なし |
| カタカナ | <#black> | 特記事項なし |
| Alphabet | <#black> | 全角は使用せず半角で統一する |
| 123 |   | 全角は使用せず半角で統一する |
| 半角丸括弧 | () | ・英文において使用する \n ・前後にスペースを入れる |
| 中黒 | ・ | ・リスト \n 同様の意味合いを持った単語及び関連のある単語の羅列（東京・大阪、小・中学校）\n ・人名のカタカナ英語 \n ・タイトル等は公式に依存 |
end title

@enduml
