@startuml

hide circle
hide empty fields
hide empty methods

skinparam class {
    backGroundColor white
    borderColor black
    arrowColor black
}

skinparam package {
    style rectangle
}

skinparam {
    shadowing false
    ranksep 30
    dpi 300
    arrowThickness 1
    defaultFontSize 12
    arrowFontSize 8
}

package "Notes" {
    class "TEST" as test
    class "Logseq" as logseq
    package "Dropbox (Obsidian)" as dropbox{
        class "SVG" as svg
        class "diagrams.net" as diagramsnet {
            by VS Code
        }
        class "Excalidraw" as excalidraw {
            by VS Code
        }
        class "Plant UML" as plantuml {
            by VS Code
        }
        class "Affinity" as affinity {
            ・Photos
            ・Designer
            ・Publisher
        }
    }
    package "Google Drive" as googledrive {
        class "Google Sheets" as googlesheets
    }
    package "Eagle" as eagle {
        class "PDF" as pdf
    }
    package "Gyazo" as gyazo {
        class "Image Files" as imagefiles
    }
    class "Coda" as coda
    class "Dynalist" as dynalist 
    class "Google Keep" as googlekeep
    class "Workflowy" as workflowy
}

package "Database" {
    class "Obsidian" as obsidian
    class "Coda" as coda2
}

package "Task Management" {
    class "Coda" as coda3
    class "Todoist" as todoist
    class "Google Calendar" as googlecalendar
    class "Gmail" as gmail
    class "Discord" as discord
}

'Notes
logseq <-- svg
plantuml -u> svg
excalidraw -u-> svg
diagramsnet -u-> svg
affinity -> svg
googlesheets -u--> diagramsnet
logseq <-u- pdf
imagefiles --> logseq
coda -> logseq

'Database

'Task Management
googlecalendar -- todoist
gmail <-u- googlecalendar
gmail --> discord
todoist -u> coda3






@enduml